<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_task_left</name>
   <tag></tag>
   <elementGuidId>0dedd17e-2a28-4236-ae3b-9e695f4203b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>55b41ea0-7dad-41b6-b038-956db5c3d76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> text-gray-500 px-2 py-3</value>
      <webElementGuid>309e4eb5-3cf8-40ad-ba82-ba74ff7c1358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 task left </value>
      <webElementGuid>7cbb9bdf-93b9-4c9f-92cd-dff6c0759195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;hero bg-gray-100 h-screen md:min-h-[700px]  w-full m-auto flex flex-col items-center transition-all duration-500&quot;]/div[@class=&quot;flex flex-col space-y-6 w-[600px] md:w-[100%] z-10 p-4 text-black&quot;]/div[@class=&quot;scroll bg-white w-full h-[400px] md:h-[500px] px-2 overflow-y-scroll rounded-md shadow-lg relative transition-all duration-500&quot;]/div[@class=&quot;w-full overflow-hidden mb- sticky top-0 bg-white flex items-center justify-between text-gray-500 border-b transition-all duration-500&quot;]/p[@class=&quot;text-gray-500 px-2 py-3&quot;]</value>
      <webElementGuid>fc6a0650-dd06-4c68-a39f-7c1da50bf261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/p</value>
      <webElementGuid>6616d5e8-66b1-4754-9fc4-84b27d9d017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::p[1]</value>
      <webElementGuid>f18b8201-cad4-4bdd-a3fa-329fb869ac29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BDD Testing'])[1]/following::p[1]</value>
      <webElementGuid>16ff9ccb-2e7f-4061-93ca-5f4f9b1948c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear all tasks'])[1]/preceding::p[1]</value>
      <webElementGuid>aebba531-089e-4380-91a5-c98e9b7b2f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[1]/preceding::p[1]</value>
      <webElementGuid>3e29057e-f64a-49cb-90a4-6205c282d9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>d8823b9d-6efe-44be-b7b6-6266862ea09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>ae89b2e4-8f8f-4844-876f-71d36e8e0abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '1 task left ' or . = '1 task left ')]</value>
      <webElementGuid>1193d337-0e3f-46d4-b26a-996ef927bbec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
